/**
 * The character catalog (owner decision 2026-10-05): 11 categories × 20 free companions, all drawn
 * in the roster's chibi style with the same five drawings and animated like Chalito. The original
 * six are spread into their categories (Chalito → people, the five animals → animals).
 *
 * This is the single source of truth for ids, categories, names and blurbs; the art prompts live
 * with the generator (apps/avatar-jobs/scripts/catalog.ts). Ids are permanent (they are stored in
 * chalito.companions.avatar and must match its CHECK '^[a-z0-9_-]{1,64}$').
 */
export const CATEGORIES = [
  { id: "animals", label: { es: "Animales", en: "Animals" } },
  { id: "people", label: { es: "Personas", en: "People" } },
  { id: "food", label: { es: "Comida", en: "Food" } },
  { id: "sports", label: { es: "Deportes", en: "Sports" } },
  { id: "professions", label: { es: "Profesiones", en: "Professions" } },
  { id: "emotions", label: { es: "Emociones", en: "Emotions" } },
  { id: "objects", label: { es: "Objetos", en: "Objects" } },
  { id: "mexican", label: { es: "México", en: "Mexico" } },
  { id: "fantasy", label: { es: "Fantasía", en: "Fantasy" } },
  { id: "space", label: { es: "Vehículos y espacio", en: "Vehicles & space" } },
  { id: "seasons", label: { es: "Temporadas y fiestas", en: "Seasons & holidays" } },
] as const;
export type Category = (typeof CATEGORIES)[number]["id"];

export interface CatalogEntry {
  id: string;
  category: Category;
  name: { es: string; en: string };
  /** Short description for the picker and onboarding. */
  blurb: { es: string; en: string };
}

export const CATALOG = [
  // Animals: the five original animal companions plus fifteen new ones.
  {
    id: "bruno",
    category: "animals",
    name: { es: "Bruno", en: "Bruno" },
    blurb: { es: "Un osito tranquilo y paciente.", en: "A calm, patient bear." },
  },
  {
    id: "luna",
    category: "animals",
    name: { es: "Luna", en: "Luna" },
    blurb: { es: "Una gatita curiosa.", en: "A curious kitten." },
  },
  {
    id: "tito",
    category: "animals",
    name: { es: "Tito", en: "Tito" },
    blurb: { es: "Un búho atento a todo.", en: "An owl who notices everything." },
  },
  {
    id: "canela",
    category: "animals",
    name: { es: "Canela", en: "Canela" },
    blurb: { es: "Una zorrita lista y rápida.", en: "A quick, clever fox." },
  },
  {
    id: "nube",
    category: "animals",
    name: { es: "Nube", en: "Nube" },
    blurb: { es: "Una conejita suave y alegre.", en: "A soft, cheerful bunny." },
  },
  {
    id: "firulais",
    category: "animals",
    name: { es: "Firulais", en: "Firulais" },
    blurb: { es: "Un perrito leal y juguetón.", en: "A loyal, playful puppy." },
  },
  {
    id: "bambu",
    category: "animals",
    name: { es: "Bambú", en: "Bambu" },
    blurb: { es: "Un panda que nunca tiene prisa.", en: "A panda who's never in a hurry." },
  },
  {
    id: "pinguino",
    category: "animals",
    name: { es: "Pingo", en: "Pingo" },
    blurb: { es: "Un pingüino elegante y torpe.", en: "A dapper, clumsy penguin." },
  },
  {
    id: "koala",
    category: "animals",
    name: { es: "Koko", en: "Koko" },
    blurb: { es: "Una koala que da los mejores abrazos.", en: "A koala who gives the best hugs." },
  },
  {
    id: "axo",
    category: "animals",
    name: { es: "Axo", en: "Axo" },
    blurb: { es: "Un ajolote que siempre sonríe.", en: "An axolotl who's always smiling." },
  },
  {
    id: "tortu",
    category: "animals",
    name: { es: "Tortu", en: "Tortu" },
    blurb: { es: "Una tortuga sabia y sin estrés.", en: "A wise, stress-free turtle." },
  },
  {
    id: "trompi",
    category: "animals",
    name: { es: "Trompi", en: "Trompi" },
    blurb: { es: "Una elefantita que nunca olvida.", en: "A little elephant who never forgets." },
  },
  {
    id: "jirafa",
    category: "animals",
    name: { es: "Jacinta", en: "Jacinta" },
    blurb: { es: "Una jirafa que ve todo desde arriba.", en: "A giraffe who sees it all from above." },
  },
  {
    id: "leo",
    category: "animals",
    name: { es: "Leo", en: "Leo" },
    blurb: { es: "Un leoncito valiente.", en: "A brave little lion." },
  },
  {
    id: "chango",
    category: "animals",
    name: { es: "Chango", en: "Chango" },
    blurb: { es: "Un monito travieso.", en: "A mischievous little monkey." },
  },
  {
    id: "rana",
    category: "animals",
    name: { es: "Rita", en: "Rita" },
    blurb: { es: "Una ranita brincona.", en: "A bouncy little frog." },
  },
  {
    id: "pulpo",
    category: "animals",
    name: { es: "Pulpi", en: "Pulpi" },
    blurb: { es: "Un pulpo que hace ocho cosas a la vez.", en: "An octopus who multitasks with eight arms." },
  },
  {
    id: "cochi",
    category: "animals",
    name: { es: "Cochi", en: "Cochi" },
    blurb: { es: "Una cerdita alegre y glotona.", en: "A cheerful, foodie piglet." },
  },
  {
    id: "pato",
    category: "animals",
    name: { es: "Paco", en: "Paco" },
    blurb: { es: "Un patito con mucha personalidad.", en: "A duckling with big personality." },
  },
  {
    id: "perezoso",
    category: "animals",
    name: { es: "Lento", en: "Lento" },
    blurb: { es: "Un perezoso que te recuerda descansar.", en: "A sloth who reminds you to rest." },
  },
  // People: Chalito leads.
  {
    id: "chalito",
    category: "people",
    name: { es: "Chalito", en: "Chalito" },
    blurb: { es: "Tu compañero de siempre.", en: "Your everyday companion." },
  },
  {
    id: "abuela",
    category: "people",
    name: { es: "Doña Chela", en: "Granny Chela" },
    blurb: { es: "Una abuelita con consejos para todo.", en: "A granny with advice for everything." },
  },
  {
    id: "abuelo",
    category: "people",
    name: { es: "Don Beto", en: "Grandpa Beto" },
    blurb: { es: "Un abuelo con mil historias.", en: "A grandpa with a thousand stories." },
  },
  {
    id: "bebe",
    category: "people",
    name: { es: "Bebé Lalo", en: "Baby Lalo" },
    blurb: { es: "Un bebé que todo lo descubre.", en: "A baby discovering everything." },
  },
  {
    id: "sofi",
    category: "people",
    name: { es: "Sofi", en: "Sofi" },
    blurb: { es: "Una niña con energía infinita.", en: "A girl with endless energy." },
  },
  {
    id: "skater",
    category: "people",
    name: { es: "Max", en: "Max" },
    blurb: { es: "Un skater relajado.", en: "A laid-back skater." },
  },
  {
    id: "gamer",
    category: "people",
    name: { es: "Pixel", en: "Pixel" },
    blurb: { es: "Una gamer que nunca pierde.", en: "A gamer who never loses." },
  },
  {
    id: "artista",
    category: "people",
    name: { es: "Pinta", en: "Pinta" },
    blurb: { es: "Una artista llena de color.", en: "An artist full of color." },
  },
  {
    id: "rockero",
    category: "people",
    name: { es: "Rocko", en: "Rocko" },
    blurb: { es: "Un rockero de buen corazón.", en: "A rocker with a big heart." },
  },
  {
    id: "bailarina",
    category: "people",
    name: { es: "Bela", en: "Bela" },
    blurb: { es: "Una bailarina elegante.", en: "A graceful dancer." },
  },
  {
    id: "hipster",
    category: "people",
    name: { es: "Brayan", en: "Brayan" },
    blurb: { es: "Un barbón amante del café.", en: "A bearded coffee lover." },
  },
  {
    id: "mama",
    category: "people",
    name: { es: "Mamá Lupita", en: "Mom Lupita" },
    blurb: { es: "Una mamá que siempre te apoya.", en: "A mom who always has your back." },
  },
  {
    id: "papa",
    category: "people",
    name: { es: "Papá Toño", en: "Dad Toño" },
    blurb: { es: "Un papá con chistes malos.", en: "A dad with terrible jokes." },
  },
  {
    id: "estudiante",
    category: "people",
    name: { es: "Valeria", en: "Valeria" },
    blurb: { es: "Una estudiante aplicada.", en: "A dedicated student." },
  },
  {
    id: "deportista",
    category: "people",
    name: { es: "Diego", en: "Diego" },
    blurb: { es: "Un chavo que no para de moverse.", en: "A guy always on the move." },
  },
  {
    id: "nerd",
    category: "people",
    name: { es: "Memo", en: "Memo" },
    blurb: { es: "Un genio de las computadoras.", en: "A computer whiz." },
  },
  {
    id: "influencer",
    category: "people",
    name: { es: "Kimmy", en: "Kimmy" },
    blurb: { es: "Una influencer siempre en tendencia.", en: "An influencer always on trend." },
  },
  {
    id: "viajero",
    category: "people",
    name: { es: "Tomás", en: "Tomas" },
    blurb: { es: "Un mochilero que conoce el mundo.", en: "A backpacker who's seen the world." },
  },
  {
    id: "dj",
    category: "people",
    name: { es: "DJ Neón", en: "DJ Neon" },
    blurb: { es: "Una DJ que pone ambiente.", en: "A DJ who sets the vibe." },
  },
  {
    id: "rapero",
    category: "people",
    name: { es: "MC Chuy", en: "MC Chuy" },
    blurb: { es: "Un rapero con rimas para todo.", en: "A rapper with a rhyme for everything." },
  },
  // Food.
  {
    id: "taquito",
    category: "food",
    name: { es: "Taquito", en: "Taquito" },
    blurb: { es: "Un taco al pastor con mucho sabor.", en: "A flavor-packed al pastor taco." },
  },
  {
    id: "concha",
    category: "food",
    name: { es: "Conchita", en: "Conchita" },
    blurb: { es: "Un pan dulce de concha.", en: "A sweet concha bun." },
  },
  {
    id: "aguacate",
    category: "food",
    name: { es: "Aguacatín", en: "Avocadito" },
    blurb: { es: "Un aguacate buena onda.", en: "A chill avocado." },
  },
  {
    id: "elote",
    category: "food",
    name: { es: "Elotito", en: "Elotito" },
    blurb: { es: "Un elote con mayonesa y chile.", en: "A corn cob with mayo and chili." },
  },
  {
    id: "pizza",
    category: "food",
    name: { es: "Peperoni", en: "Peperoni" },
    blurb: { es: "Una rebanada de pizza feliz.", en: "A happy pizza slice." },
  },
  {
    id: "sushi",
    category: "food",
    name: { es: "Maki", en: "Maki" },
    blurb: { es: "Un sushi pequeñito y ordenado.", en: "A tiny, tidy sushi roll." },
  },
  {
    id: "dona",
    category: "food",
    name: { es: "Dony", en: "Dony" },
    blurb: { es: "Una dona con chispitas.", en: "A sprinkled donut." },
  },
  {
    id: "helado",
    category: "food",
    name: { es: "Nieve", en: "Scoop" },
    blurb: { es: "Un helado que nunca se derrite.", en: "An ice cream that never melts." },
  },
  {
    id: "hamburguesa",
    category: "food",
    name: { es: "Burgui", en: "Burgy" },
    blurb: { es: "Una hamburguesa bien armada.", en: "A well-stacked burger." },
  },
  {
    id: "papas",
    category: "food",
    name: { es: "Papita", en: "Fry Guy" },
    blurb: { es: "Unas papas fritas crujientes.", en: "Crispy french fries." },
  },
  {
    id: "fresa",
    category: "food",
    name: { es: "Fresi", en: "Berry" },
    blurb: { es: "Una fresa dulce y tierna.", en: "A sweet strawberry." },
  },
  {
    id: "platano",
    category: "food",
    name: { es: "Platanito", en: "Banano" },
    blurb: { es: "Un plátano siempre de buenas.", en: "A banana always in a good mood." },
  },
  {
    id: "tamal",
    category: "food",
    name: { es: "Tamalito", en: "Tamalito" },
    blurb: { es: "Un tamal calientito.", en: "A warm little tamale." },
  },
  {
    id: "churro",
    category: "food",
    name: { es: "Churri", en: "Churro" },
    blurb: { es: "Un churro con azúcar y canela.", en: "A cinnamon-sugar churro." },
  },
  {
    id: "cafe",
    category: "food",
    name: { es: "Cafecito", en: "Coffee Cup" },
    blurb: { es: "Un cafecito que te despierta.", en: "A coffee to wake you up." },
  },
  {
    id: "galleta",
    category: "food",
    name: { es: "Galletón", en: "Cookie" },
    blurb: { es: "Una galleta con chispas.", en: "A chocolate chip cookie." },
  },
  {
    id: "pan",
    category: "food",
    name: { es: "Bolillo", en: "Bolillo" },
    blurb: { es: "Un bolillo recién horneado.", en: "A fresh-baked bread roll." },
  },
  {
    id: "sandia",
    category: "food",
    name: { es: "Sandi", en: "Melony" },
    blurb: { es: "Una sandía refrescante.", en: "A refreshing watermelon." },
  },
  {
    id: "brocoli",
    category: "food",
    name: { es: "Brócoli", en: "Brocco" },
    blurb: { es: "Un brócoli fuerte y sano.", en: "A strong, healthy broccoli." },
  },
  {
    id: "pastel",
    category: "food",
    name: { es: "Pastelito", en: "Cupcake" },
    blurb: { es: "Un pastelito de fiesta.", en: "A party cupcake." },
  },
  // Sports.
  {
    id: "futbolista",
    category: "sports",
    name: { es: "Golazo", en: "Golazo" },
    blurb: { es: "Un futbolista que celebra cada gol.", en: "A footballer who celebrates every goal." },
  },
  {
    id: "basquet",
    category: "sports",
    name: { es: "Clavada", en: "Dunk" },
    blurb: { es: "Una basquetbolista que salta alto.", en: "A basketball player who jumps high." },
  },
  {
    id: "beisbol",
    category: "sports",
    name: { es: "Jonrón", en: "Homer" },
    blurb: { es: "Un beisbolista de grandes ligas.", en: "A big-league baseball player." },
  },
  {
    id: "tenista",
    category: "sports",
    name: { es: "Raqueta", en: "Ace" },
    blurb: { es: "Una tenista con saque imparable.", en: "A tennis player with an unstoppable serve." },
  },
  {
    id: "nadador",
    category: "sports",
    name: { es: "Delfín", en: "Splash" },
    blurb: { es: "Un nadador veloz.", en: "A speedy swimmer." },
  },
  {
    id: "boxeador",
    category: "sports",
    name: { es: "Campeón", en: "Champ" },
    blurb: { es: "Un boxeador con gran corazón.", en: "A boxer with a big heart." },
  },
  {
    id: "luchador",
    category: "sports",
    name: { es: "Místico", en: "Mystic" },
    blurb: { es: "Un luchador enmascarado.", en: "A masked wrestler." },
  },
  {
    id: "ciclista",
    category: "sports",
    name: { es: "Pedalín", en: "Pedal" },
    blurb: { es: "Un ciclista que no se cansa.", en: "A cyclist who never tires." },
  },
  {
    id: "corredora",
    category: "sports",
    name: { es: "Rayo", en: "Bolt" },
    blurb: { es: "Una corredora rapidísima.", en: "A super-fast runner." },
  },
  {
    id: "gimnasta",
    category: "sports",
    name: { es: "Gimi", en: "Gymmy" },
    blurb: { es: "Una gimnasta flexible.", en: "A flexible gymnast." },
  },
  {
    id: "surfista",
    category: "sports",
    name: { es: "Ola", en: "Wave" },
    blurb: { es: "Un surfista con buena vibra.", en: "A surfer with good vibes." },
  },
  {
    id: "patinadora",
    category: "sports",
    name: { es: "Patín", en: "Skates" },
    blurb: { es: "Una patinadora sobre hielo.", en: "An ice skater." },
  },
  {
    id: "karateca",
    category: "sports",
    name: { es: "Kata", en: "Kata" },
    blurb: { es: "Un karateca disciplinado.", en: "A disciplined karateka." },
  },
  {
    id: "golfista",
    category: "sports",
    name: { es: "Birdie", en: "Birdie" },
    blurb: { es: "Un golfista muy tranquilo.", en: "A very calm golfer." },
  },
  {
    id: "portero",
    category: "sports",
    name: { es: "Atajadas", en: "Keeper" },
    blurb: { es: "Un portero que todo lo para.", en: "A goalkeeper who stops everything." },
  },
  {
    id: "voleibol",
    category: "sports",
    name: { es: "Remate", en: "Spike" },
    blurb: { es: "Una voleibolista con gran remate.", en: "A volleyball player with a mighty spike." },
  },
  {
    id: "escalador",
    category: "sports",
    name: { es: "Cumbre", en: "Summit" },
    blurb: { es: "Un escalador sin miedo.", en: "A fearless climber." },
  },
  {
    id: "ajedrez",
    category: "sports",
    name: { es: "Jaque", en: "Check" },
    blurb: { es: "Una ajedrecista que piensa todo.", en: "A chess player who thinks it all through." },
  },
  {
    id: "yoga",
    category: "sports",
    name: { es: "Zen", en: "Zen" },
    blurb: { es: "Una yogui en calma.", en: "A calm yogi." },
  },
  {
    id: "futbolamericano",
    category: "sports",
    name: { es: "Touchdown", en: "Touchdown" },
    blurb: { es: "Un jugador de americano.", en: "An American football player." },
  },
  // Professions.
  {
    id: "doctora",
    category: "professions",
    name: { es: "Dra. Salud", en: "Dr. Health" },
    blurb: { es: "Una doctora que te cuida.", en: "A doctor who looks after you." },
  },
  {
    id: "enfermero",
    category: "professions",
    name: { es: "Enfermero Ramón", en: "Nurse Ramon" },
    blurb: { es: "Un enfermero atento.", en: "An attentive nurse." },
  },
  {
    id: "abogada",
    category: "professions",
    name: { es: "Lic. Justa", en: "Attorney Justa" },
    blurb: { es: "Una abogada que defiende tus derechos.", en: "A lawyer who defends your rights." },
  },
  {
    id: "bombero",
    category: "professions",
    name: { es: "Bombero Fuego", en: "Firefighter Blaze" },
    blurb: { es: "Un bombero valiente.", en: "A brave firefighter." },
  },
  {
    id: "policia",
    category: "professions",
    name: { es: "Oficial Paz", en: "Officer Paz" },
    blurb: { es: "Una oficial que protege.", en: "An officer who protects." },
  },
  {
    id: "chef",
    category: "professions",
    name: { es: "Chef Pepe", en: "Chef Pepe" },
    blurb: { es: "Un chef con recetas secretas.", en: "A chef with secret recipes." },
  },
  {
    id: "maestra",
    category: "professions",
    name: { es: "Maestra Rosy", en: "Teacher Rosy" },
    blurb: { es: "Una maestra paciente.", en: "A patient teacher." },
  },
  {
    id: "astronauta",
    category: "professions",
    name: { es: "Astro", en: "Astro" },
    blurb: { es: "Un astronauta curioso.", en: "A curious astronaut." },
  },
  {
    id: "cientifica",
    category: "professions",
    name: { es: "Dra. Átomo", en: "Dr. Atom" },
    blurb: { es: "Una científica que experimenta.", en: "A scientist who experiments." },
  },
  {
    id: "programador",
    category: "professions",
    name: { es: "Dev", en: "Dev" },
    blurb: { es: "Un programador que arregla bugs.", en: "A programmer who squashes bugs." },
  },
  {
    id: "constructor",
    category: "professions",
    name: { es: "Ingeniero Toño", en: "Builder Tony" },
    blurb: { es: "Un constructor que hace de todo.", en: "A builder who can make anything." },
  },
  {
    id: "piloto",
    category: "professions",
    name: { es: "Capitana Nubes", en: "Captain Sky" },
    blurb: { es: "Una piloto de avión.", en: "An airline pilot." },
  },
  {
    id: "veterinaria",
    category: "professions",
    name: { es: "Vet Mimi", en: "Vet Mimi" },
    blurb: { es: "Una veterinaria que ama a los animales.", en: "A vet who loves animals." },
  },
  {
    id: "cartero",
    category: "professions",
    name: { es: "Cartero Lucho", en: "Mailman Lucho" },
    blurb: { es: "Un cartero siempre puntual.", en: "An always-punctual mail carrier." },
  },
  {
    id: "granjero",
    category: "professions",
    name: { es: "Don Pancho", en: "Farmer Pancho" },
    blurb: { es: "Un granjero trabajador.", en: "A hardworking farmer." },
  },
  {
    id: "dentista",
    category: "professions",
    name: { es: "Dra. Sonrisa", en: "Dr. Smile" },
    blurb: { es: "Una dentista que cuida tu sonrisa.", en: "A dentist who cares for your smile." },
  },
  {
    id: "mecanico",
    category: "professions",
    name: { es: "Mecánico Nacho", en: "Mechanic Nacho" },
    blurb: { es: "Un mecánico que lo arregla todo.", en: "A mechanic who fixes everything." },
  },
  {
    id: "detective",
    category: "professions",
    name: { es: "Detective Lupa", en: "Detective Lens" },
    blurb: { es: "Una detective que resuelve misterios.", en: "A detective who solves mysteries." },
  },
  {
    id: "fotografa",
    category: "professions",
    name: { es: "Foto Fer", en: "Photo Fer" },
    blurb: { es: "Una fotógrafa que captura momentos.", en: "A photographer who captures moments." },
  },
  {
    id: "contador",
    category: "professions",
    name: { es: "Contador Rubén", en: "Accountant Ruben" },
    blurb: { es: "Un contador que cuadra todo.", en: "An accountant who balances everything." },
  },
  // Emotions: little blob creatures that each embody one feeling.
  {
    id: "alegria",
    category: "emotions",
    name: { es: "Alegría", en: "Joy" },
    blurb: { es: "Pura felicidad.", en: "Pure happiness." },
  },
  {
    id: "calma",
    category: "emotions",
    name: { es: "Calma", en: "Calm" },
    blurb: { es: "Respira profundo.", en: "Take a deep breath." },
  },
  {
    id: "amor",
    category: "emotions",
    name: { es: "Amor", en: "Love" },
    blurb: { es: "Todo corazón.", en: "All heart." },
  },
  {
    id: "valentia",
    category: "emotions",
    name: { es: "Valentía", en: "Courage" },
    blurb: { es: "Nada lo detiene.", en: "Nothing stops it." },
  },
  {
    id: "curiosidad",
    category: "emotions",
    name: { es: "Curiosidad", en: "Curiosity" },
    blurb: { es: "Siempre pregunta por qué.", en: "Always asking why." },
  },
  {
    id: "esperanza",
    category: "emotions",
    name: { es: "Esperanza", en: "Hope" },
    blurb: { es: "Siempre ve la luz.", en: "Always sees the light." },
  },
  {
    id: "gratitud",
    category: "emotions",
    name: { es: "Gratitud", en: "Gratitude" },
    blurb: { es: "Agradece todo.", en: "Thankful for everything." },
  },
  {
    id: "orgullo",
    category: "emotions",
    name: { es: "Orgullo", en: "Pride" },
    blurb: { es: "Celebra tus logros.", en: "Celebrates your wins." },
  },
  {
    id: "nervios",
    category: "emotions",
    name: { es: "Nervios", en: "Jitters" },
    blurb: { es: "Un poquito nervioso.", en: "A little bit nervous." },
  },
  {
    id: "enojo",
    category: "emotions",
    name: { es: "Enojo", en: "Grumpy" },
    blurb: { es: "Gruñón pero buena onda.", en: "Grumpy but good-hearted." },
  },
  {
    id: "tristeza",
    category: "emotions",
    name: { es: "Melancolía", en: "Blue" },
    blurb: { es: "Te acompaña en días grises.", en: "Keeps you company on grey days." },
  },
  {
    id: "sorpresa",
    category: "emotions",
    name: { es: "Sorpresa", en: "Wow" },
    blurb: { es: "Todo le asombra.", en: "Amazed by everything." },
  },
  {
    id: "sueno",
    category: "emotions",
    name: { es: "Sueño", en: "Sleepy" },
    blurb: { es: "Siempre lista para una siesta.", en: "Always ready for a nap." },
  },
  {
    id: "risa",
    category: "emotions",
    name: { es: "Risa", en: "Giggles" },
    blurb: { es: "No para de reír.", en: "Can't stop laughing." },
  },
  {
    id: "paz",
    category: "emotions",
    name: { es: "Paz", en: "Peace" },
    blurb: { es: "Tranquilidad total.", en: "Total serenity." },
  },
  {
    id: "emocion",
    category: "emotions",
    name: { es: "Emoción", en: "Hype" },
    blurb: { es: "¡Súper emocionada!", en: "Super hyped!" },
  },
  {
    id: "timidez",
    category: "emotions",
    name: { es: "Timidez", en: "Shy" },
    blurb: { es: "Tímida pero tierna.", en: "Shy but sweet." },
  },
  {
    id: "confianza",
    category: "emotions",
    name: { es: "Confianza", en: "Confidence" },
    blurb: { es: "Cree en ti.", en: "Believes in you." },
  },
  {
    id: "nostalgia",
    category: "emotions",
    name: { es: "Nostalgia", en: "Nostalgia" },
    blurb: { es: "Recuerda los buenos tiempos.", en: "Remembers the good times." },
  },
  {
    id: "ternura",
    category: "emotions",
    name: { es: "Ternura", en: "Tenderness" },
    blurb: { es: "Pura ternura.", en: "Pure sweetness." },
  },
  // Objects.
  {
    id: "lampara",
    category: "objects",
    name: { es: "Lamparita", en: "Lampy" },
    blurb: { es: "Una lámpara con ideas brillantes.", en: "A lamp with bright ideas." },
  },
  {
    id: "taza",
    category: "objects",
    name: { es: "Tacita", en: "Mugsy" },
    blurb: { es: "Una taza que te acompaña.", en: "A mug that keeps you company." },
  },
  {
    id: "libro",
    category: "objects",
    name: { es: "Librito", en: "Booky" },
    blurb: { es: "Un libro lleno de historias.", en: "A book full of stories." },
  },
  {
    id: "lapiz",
    category: "objects",
    name: { es: "Lápiz", en: "Pencil" },
    blurb: { es: "Un lápiz que dibuja sueños.", en: "A pencil that draws dreams." },
  },
  {
    id: "reloj",
    category: "objects",
    name: { es: "Tic Tac", en: "Tick Tock" },
    blurb: { es: "Un reloj siempre a tiempo.", en: "A clock that's always on time." },
  },
  {
    id: "celular",
    category: "objects",
    name: { es: "Cel", en: "Phoney" },
    blurb: { es: "Un celular siempre conectado.", en: "An always-online phone." },
  },
  {
    id: "audifonos",
    category: "objects",
    name: { es: "Audi", en: "Beats" },
    blurb: { es: "Unos audífonos con ritmo.", en: "Headphones with rhythm." },
  },
  {
    id: "trompo",
    category: "objects",
    name: { es: "Trompo", en: "Spinny" },
    blurb: { es: "Un trompo mexicano que no para.", en: "A Mexican spinning top that never stops." },
  },
  {
    id: "mochila",
    category: "objects",
    name: { es: "Mochi", en: "Packy" },
    blurb: { es: "Una mochila lista para la aventura.", en: "A backpack ready for adventure." },
  },
  {
    id: "paraguas",
    category: "objects",
    name: { es: "Paragüitas", en: "Brolly" },
    blurb: { es: "Un paraguas que te protege.", en: "An umbrella that protects you." },
  },
  {
    id: "camara",
    category: "objects",
    name: { es: "Clic", en: "Clicky" },
    blurb: { es: "Una cámara que guarda recuerdos.", en: "A camera that keeps memories." },
  },
  {
    id: "planta",
    category: "objects",
    name: { es: "Maceta", en: "Sprout" },
    blurb: { es: "Una plantita que crece contigo.", en: "A little plant that grows with you." },
  },
  {
    id: "vela",
    category: "objects",
    name: { es: "Velita", en: "Candle" },
    blurb: { es: "Una velita que ilumina.", en: "A little candle that lights the way." },
  },
  {
    id: "globo",
    category: "objects",
    name: { es: "Globito", en: "Balloony" },
    blurb: { es: "Un globo que te alegra.", en: "A balloon that cheers you up." },
  },
  {
    id: "consola",
    category: "objects",
    name: { es: "Joystick", en: "Joystick" },
    blurb: { es: "Un control listo para jugar.", en: "A controller ready to play." },
  },
  {
    id: "tostadora",
    category: "objects",
    name: { es: "Tosti", en: "Toasty" },
    blurb: { es: "Una tostadora con chispa.", en: "A toaster with spark." },
  },
  {
    id: "calcetin",
    category: "objects",
    name: { es: "Calce", en: "Sock" },
    blurb: { es: "Un calcetín que perdió a su par.", en: "A sock looking for its pair." },
  },
  {
    id: "cubo",
    category: "objects",
    name: { es: "Cubi", en: "Cuby" },
    blurb: { es: "Un cubo mágico ingenioso.", en: "A clever puzzle cube." },
  },
  {
    id: "lata",
    category: "objects",
    name: { es: "Latita", en: "Canny" },
    blurb: { es: "Una lata de refresco burbujeante.", en: "A fizzy soda can." },
  },
  {
    id: "dado",
    category: "objects",
    name: { es: "Dadito", en: "Dicey" },
    blurb: { es: "Un dado con suerte.", en: "A lucky die." },
  },
  // Mexican culture.
  {
    id: "mariachi",
    category: "mexican",
    name: { es: "Mariachi Chente", en: "Mariachi Chente" },
    blurb: { es: "Un mariachi que canta con el alma.", en: "A mariachi who sings from the heart." },
  },
  {
    id: "catrina",
    category: "mexican",
    name: { es: "Catrina", en: "Catrina" },
    blurb: { es: "La catrina más elegante.", en: "The most elegant Catrina." },
  },
  {
    id: "alebrije",
    category: "mexican",
    name: { es: "Alebrije", en: "Alebrije" },
    blurb: { es: "Un alebrije de mil colores.", en: "A thousand-color alebrije." },
  },
  {
    id: "charro",
    category: "mexican",
    name: { es: "Charro Lalo", en: "Charro Lalo" },
    blurb: { es: "Un charro de gran estilo.", en: "A charro with great style." },
  },
  {
    id: "adelita",
    category: "mexican",
    name: { es: "Adelita", en: "Adelita" },
    blurb: { es: "Una adelita valiente.", en: "A brave Adelita." },
  },
  {
    id: "jarocha",
    category: "mexican",
    name: { es: "Jarocha", en: "Jarocha" },
    blurb: { es: "Bailando son jarocho.", en: "Dancing son jarocho." },
  },
  {
    id: "calaverita",
    category: "mexican",
    name: { es: "Calaverita", en: "Sugar Skull" },
    blurb: { es: "Una calaverita de azúcar.", en: "A sugar skull." },
  },
  {
    id: "pinata",
    category: "mexican",
    name: { es: "Piñata", en: "Piñata" },
    blurb: { es: "La piñata de la fiesta.", en: "The party piñata." },
  },
  {
    id: "xolo",
    category: "mexican",
    name: { es: "Xólotl", en: "Xolo" },
    blurb: { es: "Un xoloitzcuintle sabio.", en: "A wise Xolo dog." },
  },
  {
    id: "lotero",
    category: "mexican",
    name: { es: "El Gallo", en: "The Rooster" },
    blurb: { es: "Una carta de lotería viva.", en: "A living lotería card." },
  },
  {
    id: "frutero",
    category: "mexican",
    name: { es: "Don Fruta", en: "Fruit Man" },
    blurb: { es: "Fruta con chile y limón.", en: "Fruit with chili and lime." },
  },
  {
    id: "danzante",
    category: "mexican",
    name: { es: "Danzante", en: "Aztec Dancer" },
    blurb: { es: "Un danzante con penacho.", en: "A dancer with a plumed headdress." },
  },
  {
    id: "quetzal",
    category: "mexican",
    name: { es: "Quetzal", en: "Quetzal" },
    blurb: { es: "Un quetzal brillante.", en: "A brilliant quetzal." },
  },
  {
    id: "nopal",
    category: "mexican",
    name: { es: "Nopalito", en: "Nopalito" },
    blurb: { es: "Un nopal con tunas.", en: "A prickly pear cactus with fruit." },
  },
  {
    id: "chapulin",
    category: "mexican",
    name: { es: "Chapulín", en: "Grasshopper" },
    blurb: { es: "Un chapulín saltarín.", en: "A hopping grasshopper." },
  },
  {
    id: "tlaloc",
    category: "mexican",
    name: { es: "Lluvia", en: "Rainy" },
    blurb: { es: "Trae la lluvia buena.", en: "Brings the good rain." },
  },
  {
    id: "trajinera",
    category: "mexican",
    name: { es: "Xochi", en: "Xochi" },
    blurb: { es: "Paseando por Xochimilco.", en: "Cruising Xochimilco." },
  },
  {
    id: "matraca",
    category: "mexican",
    name: { es: "Matraca", en: "Matraca" },
    blurb: { es: "Hace ruido de fiesta.", en: "Makes party noise." },
  },
  {
    id: "cempasuchil",
    category: "mexican",
    name: { es: "Cempasúchil", en: "Marigold" },
    blurb: { es: "La flor del Día de Muertos.", en: "The Day of the Dead flower." },
  },
  {
    id: "pan-muerto",
    category: "mexican",
    name: { es: "Pan de Muerto", en: "Pan de Muerto" },
    blurb: { es: "Dulce tradición.", en: "A sweet tradition." },
  },
  // Fantasy & myth.
  {
    id: "dragon",
    category: "fantasy",
    name: { es: "Dragoncito", en: "Drako" },
    blurb: { es: "Un dragón pequeño pero fuerte.", en: "A small but mighty dragon." },
  },
  {
    id: "unicornio",
    category: "fantasy",
    name: { es: "Unicornia", en: "Uni" },
    blurb: { es: "Un unicornio mágico.", en: "A magical unicorn." },
  },
  {
    id: "mago",
    category: "fantasy",
    name: { es: "Mago Merlín", en: "Wizard Merl" },
    blurb: { es: "Un mago sabio.", en: "A wise wizard." },
  },
  {
    id: "bruja",
    category: "fantasy",
    name: { es: "Brujita", en: "Witchy" },
    blurb: { es: "Una brujita buena onda.", en: "A friendly little witch." },
  },
  {
    id: "hada",
    category: "fantasy",
    name: { es: "Hada Lila", en: "Fairy Lila" },
    blurb: { es: "Un hada que cumple deseos.", en: "A fairy who grants wishes." },
  },
  {
    id: "sirena",
    category: "fantasy",
    name: { es: "Marina", en: "Marina" },
    blurb: { es: "Una sirena del mar profundo.", en: "A mermaid from the deep sea." },
  },
  {
    id: "robot",
    category: "fantasy",
    name: { es: "Robi", en: "Robo" },
    blurb: { es: "Un robot amigable.", en: "A friendly robot." },
  },
  {
    id: "alien",
    category: "fantasy",
    name: { es: "Zorg", en: "Zorg" },
    blurb: { es: "Un alien que viene en paz.", en: "An alien who comes in peace." },
  },
  {
    id: "fantasma",
    category: "fantasy",
    name: { es: "Boo", en: "Boo" },
    blurb: { es: "Un fantasmita nada aterrador.", en: "A not-scary little ghost." },
  },
  {
    id: "vampiro",
    category: "fantasy",
    name: { es: "Conde Dracu", en: "Count Dracu" },
    blurb: { es: "Un vampiro vegetariano.", en: "A vegetarian vampire." },
  },
  {
    id: "caballero",
    category: "fantasy",
    name: { es: "Sir Valiente", en: "Sir Brave" },
    blurb: { es: "Un caballero noble.", en: "A noble knight." },
  },
  {
    id: "princesa",
    category: "fantasy",
    name: { es: "Princesa Estrella", en: "Princess Star" },
    blurb: { es: "Una princesa valiente.", en: "A brave princess." },
  },
  {
    id: "fenix",
    category: "fantasy",
    name: { es: "Fénix", en: "Phoenix" },
    blurb: { es: "Siempre renace.", en: "Always rises again." },
  },
  {
    id: "yeti",
    category: "fantasy",
    name: { es: "Yeti", en: "Yeti" },
    blurb: { es: "Un yeti abrazable.", en: "A huggable yeti." },
  },
  {
    id: "duende",
    category: "fantasy",
    name: { es: "Duende", en: "Gnome" },
    blurb: { es: "Un duende del bosque.", en: "A forest gnome." },
  },
  {
    id: "pegaso",
    category: "fantasy",
    name: { es: "Pegaso", en: "Pegasus" },
    blurb: { es: "Un caballo con alas.", en: "A winged horse." },
  },
  {
    id: "kraken",
    category: "fantasy",
    name: { es: "Kraky", en: "Kraky" },
    blurb: { es: "Un kraken muy tierno.", en: "A very cute kraken." },
  },
  {
    id: "ninja",
    category: "fantasy",
    name: { es: "Ninja Sombra", en: "Ninja Shadow" },
    blurb: { es: "Un ninja silencioso.", en: "A silent ninja." },
  },
  {
    id: "pirata",
    category: "fantasy",
    name: { es: "Capitán Barba", en: "Captain Beard" },
    blurb: { es: "Un pirata buscando tesoros.", en: "A pirate hunting treasure." },
  },
  {
    id: "genio",
    category: "fantasy",
    name: { es: "Genio", en: "Genie" },
    blurb: { es: "Un genio de la lámpara.", en: "A genie from the lamp." },
  },
  // Vehicles & space.
  {
    id: "cohete",
    category: "space",
    name: { es: "Cohetín", en: "Rocky Rocket" },
    blurb: { es: "Un cohete listo para despegar.", en: "A rocket ready for liftoff." },
  },
  {
    id: "planeta",
    category: "space",
    name: { es: "Saturnito", en: "Saturny" },
    blurb: { es: "Un planeta con anillos.", en: "A planet with rings." },
  },
  {
    id: "estrella",
    category: "space",
    name: { es: "Estrellita", en: "Twinkle" },
    blurb: { es: "Una estrella que brilla.", en: "A twinkling star." },
  },
  {
    id: "lunita",
    category: "space",
    name: { es: "Lunita", en: "Moony" },
    blurb: { es: "Una luna que te cuida de noche.", en: "A moon who watches over you at night." },
  },
  {
    id: "sol",
    category: "space",
    name: { es: "Solecito", en: "Sunny" },
    blurb: { es: "Un sol que calienta tu día.", en: "A sun that warms your day." },
  },
  {
    id: "cometa",
    category: "space",
    name: { es: "Cometa", en: "Comet" },
    blurb: { es: "Una cometa veloz.", en: "A speedy comet." },
  },
  {
    id: "ovni",
    category: "space",
    name: { es: "Ovni", en: "UFO" },
    blurb: { es: "Un platillo volador amistoso.", en: "A friendly flying saucer." },
  },
  {
    id: "satelite",
    category: "space",
    name: { es: "Sateli", en: "Sat" },
    blurb: { es: "Un satélite que conecta al mundo.", en: "A satellite connecting the world." },
  },
  {
    id: "astronauta-perro",
    category: "space",
    name: { es: "Laika", en: "Laika" },
    blurb: { es: "Una perrita astronauta.", en: "A space puppy." },
  },
  {
    id: "carro",
    category: "space",
    name: { es: "Carrito", en: "Zoom" },
    blurb: { es: "Un carro de carreras.", en: "A race car." },
  },
  {
    id: "camion",
    category: "space",
    name: { es: "Camioncito", en: "Trucky" },
    blurb: { es: "Un camión trabajador.", en: "A hardworking truck." },
  },
  {
    id: "tren",
    category: "space",
    name: { es: "Trenecito", en: "Choo" },
    blurb: { es: "Un tren que va a todos lados.", en: "A train that goes everywhere." },
  },
  {
    id: "avion",
    category: "space",
    name: { es: "Avioncito", en: "Jetty" },
    blurb: { es: "Un avión que vuela alto.", en: "A plane that flies high." },
  },
  {
    id: "barco",
    category: "space",
    name: { es: "Barquito", en: "Boaty" },
    blurb: { es: "Un barco navegante.", en: "A seafaring boat." },
  },
  {
    id: "helicoptero",
    category: "space",
    name: { es: "Heli", en: "Heli" },
    blurb: { es: "Un helicóptero de rescate.", en: "A rescue helicopter." },
  },
  {
    id: "submarino",
    category: "space",
    name: { es: "Submarino", en: "Subby" },
    blurb: { es: "Explora el fondo del mar.", en: "Explores the deep sea." },
  },
  {
    id: "moto",
    category: "space",
    name: { es: "Moto", en: "Vroom" },
    blurb: { es: "Una moto veloz.", en: "A speedy motorbike." },
  },
  {
    id: "bici",
    category: "space",
    name: { es: "Bicicleta", en: "Bikey" },
    blurb: { es: "Una bici paseadora.", en: "A cruising bike." },
  },
  {
    id: "agujero-negro",
    category: "space",
    name: { es: "Hoyo Negro", en: "Black Hole" },
    blurb: { es: "Un agujero negro con mucha atracción.", en: "A very attractive black hole." },
  },
  {
    id: "tierra",
    category: "space",
    name: { es: "Tierrita", en: "Earthy" },
    blurb: { es: "Nuestro planeta azul.", en: "Our blue planet." },
  },
  // Seasons & holidays.
  {
    id: "santa",
    category: "seasons",
    name: { es: "Santa", en: "Santa" },
    blurb: { es: "Trae regalos todo el año.", en: "Brings gifts all year." },
  },
  {
    id: "reno",
    category: "seasons",
    name: { es: "Reno", en: "Reindeer" },
    blurb: { es: "Un reno de nariz roja.", en: "A red-nosed reindeer." },
  },
  {
    id: "muneco-nieve",
    category: "seasons",
    name: { es: "Muñeco de Nieve", en: "Snowy" },
    blurb: { es: "Un muñeco de nieve amigable.", en: "A friendly snowman." },
  },
  {
    id: "elfo",
    category: "seasons",
    name: { es: "Elfo", en: "Elf" },
    blurb: { es: "Ayudante de Santa.", en: "Santa's helper." },
  },
  {
    id: "calabaza",
    category: "seasons",
    name: { es: "Calabacita", en: "Pumpkin" },
    blurb: { es: "Una calabaza de Halloween.", en: "A Halloween pumpkin." },
  },
  {
    id: "momia",
    category: "seasons",
    name: { es: "Momia", en: "Mummy" },
    blurb: { es: "Una momia muy tierna.", en: "A very cute mummy." },
  },
  {
    id: "conejo-pascua",
    category: "seasons",
    name: { es: "Conejo de Pascua", en: "Easter Bunny" },
    blurb: { es: "Esconde huevos de colores.", en: "Hides colorful eggs." },
  },
  {
    id: "cupido",
    category: "seasons",
    name: { es: "Cupido", en: "Cupid" },
    blurb: { es: "Flechazos de amor.", en: "Arrows of love." },
  },
  {
    id: "pavo",
    category: "seasons",
    name: { es: "Pavito", en: "Turkey" },
    blurb: { es: "Agradecido por todo.", en: "Thankful for everything." },
  },
  {
    id: "trebol",
    category: "seasons",
    name: { es: "Trébol", en: "Clover" },
    blurb: { es: "Te trae buena suerte.", en: "Brings you good luck." },
  },
  {
    id: "primavera",
    category: "seasons",
    name: { es: "Primavera", en: "Spring" },
    blurb: { es: "Florece con la primavera.", en: "Blooms with spring." },
  },
  {
    id: "verano",
    category: "seasons",
    name: { es: "Verano", en: "Summer" },
    blurb: { es: "Siempre de vacaciones.", en: "Always on vacation." },
  },
  {
    id: "otono",
    category: "seasons",
    name: { es: "Otoño", en: "Autumn" },
    blurb: { es: "Entre hojas que caen.", en: "Among falling leaves." },
  },
  {
    id: "invierno",
    category: "seasons",
    name: { es: "Invierno", en: "Winter" },
    blurb: { es: "Bien abrigadito.", en: "All bundled up." },
  },
  {
    id: "ano-nuevo",
    category: "seasons",
    name: { es: "Año Nuevo", en: "New Year" },
    blurb: { es: "¡Feliz año nuevo!", en: "Happy New Year!" },
  },
  {
    id: "rosca",
    category: "seasons",
    name: { es: "Rosca de Reyes", en: "Rosca" },
    blurb: { es: "Ojalá no te salga el niño.", en: "Hope you don't get the baby." },
  },
  {
    id: "rey-mago",
    category: "seasons",
    name: { es: "Rey Mago", en: "Wise King" },
    blurb: { es: "Trae regalos el 6 de enero.", en: "Brings gifts on January 6th." },
  },
  {
    id: "posada",
    category: "seasons",
    name: { es: "Posadita", en: "Posada" },
    blurb: { es: "Lista para la posada.", en: "Ready for the posada." },
  },
  {
    id: "pino",
    category: "seasons",
    name: { es: "Pinito", en: "Pine" },
    blurb: { es: "Un arbolito de navidad.", en: "A little Christmas tree." },
  },
  {
    id: "regalo",
    category: "seasons",
    name: { es: "Regalito", en: "Gifty" },
    blurb: { es: "Una sorpresa envuelta.", en: "A wrapped surprise." },
  },
] as const satisfies readonly CatalogEntry[];

/** Every catalog id, as a union (stored values are checked against ROSTER_IDS at runtime). */
export type CatalogId = (typeof CATALOG)[number]["id"];
