output "engine_urls" {
  description = "run.app URL per engine. Point DNS at these, or map the domain."
  value       = { for k, m in module.engine : k => m.url }
}

output "media_bucket" {
  value = google_storage_bucket.media.name
}

output "artifact_registry" {
  description = "Push images here as <this>/<slug>:<tag>."
  value       = "${var.region}-docker.pkg.dev/${var.project_id}/${google_artifact_registry_repository.engines.repository_id}"
}

output "secrets_needing_values" {
  description = <<-EOT
    Secrets still holding the REPLACE_ME placeholder. Everything else was
    generated by Terraform and already has a real value. Read from computed
    names, so a secret a partial apply never created cannot appear.
  EOT
  value = sort(concat(
    flatten([for m in module.engine : m.placeholder_secret_ids]),
    [for k in local.shared_placeholder : element(split("/", google_secret_manager_secret.shared[k].name), 3)],
  ))
}

output "worker_urls" {
  description = "Worker URL per engine that has one. The API is wired to these automatically."
  value       = { for k, m in module.engine : k => m.worker_url if m.worker_url != null }
}

output "jobs" {
  description = "Cloud Run Jobs per engine. Run one on demand with `gcloud run jobs execute <name>`."
  value       = { for k, m in module.engine : k => m.job_names if length(m.job_names) > 0 }
}

output "cloud_build_service_account" {
  description = "Pass to `gcloud builds submit --service-account=projects/<project>/serviceAccounts/<this>`."
  value       = google_service_account.deployer.email
}
