// The legal documents, their versions and how a version renders (old P6-1,
// P6-3; aceptacion-ux §8, §11 "Documentos versionados con URL fija y hash").
//
// registry.json lists every version with its publish state, effective date
// and, for Terms changes, whether the change is relevant (re-acceptance
// modal) or minor (banner). The archived text is generated by
// `pnpm legal:hash` into src/content/legal/archive/. Pure, so tests and
// `pnpm test:legal` read exactly what the pages render.

import registryJson from './registry.json' with { type: 'json' };
import { ARCHIVE, type ArchivedVersion } from '@/content/legal/archive/index';
import { bindAmounts } from './amounts';
import { blocksText, parseMarkdown, type Block } from './markdown';
import { subscriptionConsistency } from './consistency';

export type LegalDoc =
  | 'terminos'
  | 'suscripcion'
  | 'privacidad'
  | 'uso_aceptable'
  | 'paquetes'
  | 'quien_vende';
export const LEGAL_DOCS: readonly LegalDoc[] = [
  'terminos',
  'suscripcion',
  'privacidad',
  'uso_aceptable',
  'paquetes',
  'quien_vende',
];

export interface VersionMeta {
  published: boolean;
  /** ISO date the version takes effect (null while a draft). */
  effective: string | null;
  /** aceptacion-ux §8: relevant = rights, payments or data → modal. */
  relevance: 'relevant' | 'minor';
  /** Up to three one-line changes for the §8 modal (es). */
  changes: string[];
  /** Roles of amounts two roles share today, per occurrence (amounts.ts). */
  amountRoles?: Record<string, string[]>;
}

interface Entry {
  file: string;
  path: string;
  current: string;
  versions: Record<string, VersionMeta>;
}

const REGISTRY = registryJson as Record<LegalDoc, Entry>;

/** "1.0" → "v1-0" (URL segment). */
export const versionSlug = (v: string) => `v${v.replace(/\./g, '-')}`;
/** "v1-0" → "1.0", or null if it isn't a version segment. */
export function parseVersionSlug(slug: string): string | null {
  const m = /^v(\d+)-(\d+)$/.exec(slug);
  return m ? `${m[1]}.${m[2]}` : null;
}

export function legalPath(doc: LegalDoc): string {
  return REGISTRY[doc].path;
}
export function currentVersion(doc: LegalDoc): string {
  return REGISTRY[doc].current;
}
/**
 * registry.json `effective` as an instant. A full timestamp is used as is; a
 * bare date ("2026-12-01") means 00:00 in Mexico City (UTC−6 all year since
 * 2022), not UTC midnight, which would be 18:00 the day before there.
 */
export function effectiveInstant(raw: string | null): string | null {
  if (!raw) return null;
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return `${raw}T06:00:00.000Z`;
  const t = Date.parse(raw);
  return Number.isNaN(t) ? null : new Date(t).toISOString();
}

export function versionMeta(doc: LegalDoc, version = currentVersion(doc)): VersionMeta | null {
  const m = REGISTRY[doc].versions[version];
  return m ? { ...m, effective: effectiveInstant(m.effective) } : null;
}
export function listVersions(doc: LegalDoc): string[] {
  return Object.keys(REGISTRY[doc].versions).filter((v) => archived(doc, v));
}
/** A version that changes an earlier published one: its relevant changes
 *  must be announced ≥ 30 days ahead (the first version has nothing to
 *  change). */
export function noticeRequired(doc: LegalDoc, version = currentVersion(doc)): boolean {
  const n = (v: string) => v.split('.').map(Number);
  const before = (a: string, b: string) => {
    const [x, y] = [n(a), n(b)];
    for (let i = 0; i < Math.max(x.length, y.length); i++)
      if ((x[i] ?? 0) !== (y[i] ?? 0)) return (x[i] ?? 0) < (y[i] ?? 0);
    return false;
  };
  return Object.entries(REGISTRY[doc].versions).some(([v, m]) => m.published && before(v, version));
}

export function docForPath(path: string): LegalDoc | null {
  return LEGAL_DOCS.find((d) => REGISTRY[d].path === path) ?? null;
}

export function archived(doc: LegalDoc, version = currentVersion(doc)): ArchivedVersion | null {
  return ARCHIVE[doc]?.[version] ?? null;
}

/** The document's text as people see it. A published version is frozen:
 *  the text filled with the prices of the day it was archived, whose hash
 *  consent events cite (a later price change needs a new version, and
 *  `pnpm legal:hash` fails until there is one). A draft re-binds every
 *  amount from src/config/pricing.ts on each render. */
export function renderedSource(doc: LegalDoc, version = currentVersion(doc)): string | null {
  const a = archived(doc, version);
  if (!a) return null;
  return versionMeta(doc, version)?.published ? a.rendered : bindAmounts(a.template);
}

export function renderedBlocks(doc: LegalDoc, version = currentVersion(doc)): Block[] | null {
  const src = renderedSource(doc, version);
  return src === null ? null : parseMarkdown(src);
}

/** Anything Law left in brackets: owner/attorney values (`[RAZÓN SOCIAL]`,
 *  `[IVA: CONFIRMAR]`), numbers to confirm (`[30]`, `[15]`), choices
 *  (`[conservarás / tendrás limitado]`) and notes (`[NOTA PARA EL DUEÑO …]`).
 *  Runs on the rendered text, where a Markdown link is already plain text,
 *  so every remaining `[…]` is unfinished. Innermost brackets count once
 *  each; no allow-list is needed today. */
export const PLACEHOLDER_RE = /\[[^[\]]+\]/g;

/** The placeholders left in a rendered document, in order. */
export function placeholders(doc: LegalDoc, version = currentVersion(doc)): string[] {
  const blocks = renderedBlocks(doc, version);
  return blocks ? [...blocksText(blocks).matchAll(PLACEHOLDER_RE)].map((m) => m[0]) : [];
}

/** Where the current text disagrees with the config (consistency.ts). */
export function consistencyIssues(doc: LegalDoc, version = currentVersion(doc)): string[] {
  if (doc !== 'suscripcion') return [];
  const src = renderedSource(doc, version);
  return src === null ? [] : subscriptionConsistency(src);
}

/** What keeps LEGAL_PUBLISH from taking effect: any current version with a
 *  placeholder, missing from the archive, not marked published, or out of
 *  step with the config. */
export function legalPublishBlockers(): string[] {
  const out: string[] = [];
  for (const doc of LEGAL_DOCS) {
    const v = currentVersion(doc);
    if (!archived(doc, v)) out.push(`${doc}@${v}:not-archived`);
    if (!versionMeta(doc, v)?.published) out.push(`${doc}@${v}:draft`);
    const left = placeholders(doc, v).length;
    if (left) out.push(`${doc}@${v}:${left}-placeholders`);
    for (const issue of consistencyIssues(doc, v)) out.push(`${doc}@${v}:${issue}`);
  }
  return out;
}
