-- =====================================================================
-- Chalyb — register Chalito as an engine.
--
-- Generated by scripts/new-engine.mjs. The rest of the checklist is in
-- docs/infra/adding-an-engine.md.
--
-- Ships as 'coming_soon' on purpose: the launch guard in
-- src/app/auth/launch/[slug]/route.ts refuses to send users to a non-active
-- engine, so nobody can reach a backend that is not serving yet. Flip to
-- 'active' once chalito.chalyb.com resolves and the secrets have values.
--
-- Idempotent: re-runnable.
-- =====================================================================

insert into public.engines
  (id, org_id, slug, name, icon, category, type, env, region, node,
   description, featured, status, tier_required)
values
  ('9c15cd43-7ff8-4b6f-90f5-0d56203111de',
   '00000000-0000-0000-0000-000000000001',
   'chalito', 'Chalito', '🐻', 'AGENTS', 'Agent',
   'PRODUCTION', 'us-central1', 'run-1',
   'Tu compañero animado: dirige a tu equipo de IA, te avisa por voz, push, WhatsApp o llamada, y conoce a los compañeros de tu familia y equipo.',
   false, 'coming_soon', 'PRO')
-- Conflict on the natural key (org_id, slug), not the generated id: that
-- makes the migration idempotent even if it is re-run after the row was
-- created some other way.
on conflict (org_id, slug) do update set
  name        = excluded.name,
  description = excluded.description,
  icon        = excluded.icon;

-- external_url / admin_api_base wire the SSO + provisioning contract.
-- Separate statement so re-running after a domain change updates in place.
-- Chalito splits the two: the web app (external_url, /auth/sso) is on Vercel at
-- chalito.chalyb.com, and its api (admin_api_base: POST /tenants, /tenants/{id}/status)
-- is the engine's Cloud Run service at api.chalito.chalyb.com.
update public.engines
set integration_mode      = 'external_sso_redirect',
    external_url          = 'https://chalito.chalyb.com',
    admin_api_base        = 'https://api.chalito.chalyb.com',
    requires_provisioning = true
where slug = 'chalito';
