// GENERATED from picassoglitch/chalito recipes/catalog.json @ f9c9bab (v1, 1791271724830).
// Only what the hub shows; commands, paths and installers stay in the agent's signed catalog.
// Regenerate when the curated catalog changes.
import type { RecipeKind } from '@chalito/protocol';

export interface CatalogApp {
  id: string;
  name: string;
  vendor: string;
  homepage: string;
  kinds: readonly RecipeKind[];
  /** agent: a coding agent Chalito runs sessions with; desktop/web: an app it opens on that computer. */
  group: 'agent' | 'desktop' | 'web';
  /** The app's own plan sign-in on that computer: on, team only, or not offered. */
  planSignin: 'on' | 'owner_only' | 'off';
  /** Has an official installer the computer can run (after a local confirm). */
  installable: boolean;
  /** Chalito can start sessions with it (claude-sdk / codex / acp). */
  sessions: boolean;
  apiKey?: { label: string; docsUrl: string };
}

export const CATALOG: readonly CatalogApp[] = [
  {
    id: 'aider',
    name: 'Aider',
    vendor: 'Aider (Paul Gauthier)',
    homepage: 'https://aider.chat/',
    kinds: ['terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: false,
    apiKey: {
      label: 'OpenAI API key (aider also reads ANTHROPIC_API_KEY, OPENROUTER_API_KEY, etc.)',
      docsUrl: 'https://aider.chat/docs/config/api-keys.html',
    },
  },
  {
    id: 'chatgpt-desktop',
    name: 'ChatGPT (desktop)',
    vendor: 'OpenAI',
    homepage: 'https://chatgpt.com/',
    kinds: ['desktop-app'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    vendor: 'OpenAI',
    homepage: 'https://chatgpt.com/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    vendor: 'Anthropic',
    homepage: 'https://www.claude.com/product/claude-code',
    kinds: ['claude-sdk', 'terminal'],
    group: 'agent',
    planSignin: 'owner_only',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'Anthropic API key',
      docsUrl: 'https://docs.claude.com/en/api/admin-api/apikeys/get-api-key',
    },
  },
  {
    id: 'claude-desktop',
    name: 'Claude (desktop)',
    vendor: 'Anthropic',
    homepage: 'https://claude.com/download',
    kinds: ['desktop-app'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
  {
    id: 'claude-web',
    name: 'Claude',
    vendor: 'Anthropic',
    homepage: 'https://claude.ai/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'codex',
    name: 'Codex',
    vendor: 'OpenAI',
    homepage: 'https://developers.openai.com/codex',
    kinds: ['codex', 'terminal'],
    group: 'agent',
    planSignin: 'owner_only',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'OpenAI API key',
      docsUrl: 'https://platform.openai.com/api-keys',
    },
  },
  {
    id: 'copilot-cli',
    name: 'GitHub Copilot CLI',
    vendor: 'GitHub',
    homepage: 'https://github.com/github/copilot-cli',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'GitHub fine-grained token with "Copilot Requests" permission',
      docsUrl: 'https://docs.github.com/en/copilot/how-tos/set-up/install-copilot-cli',
    },
  },
  {
    id: 'copilot-web',
    name: 'Microsoft Copilot',
    vendor: 'Microsoft',
    homepage: 'https://copilot.microsoft.com/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'cursor-cli',
    name: 'Cursor CLI',
    vendor: 'Anysphere',
    homepage: 'https://cursor.com/docs/cli/overview',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'Cursor API key',
      docsUrl: 'https://cursor.com/docs/cli/reference/authentication',
    },
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    homepage: 'https://cursor.com/',
    kinds: ['desktop-app'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    vendor: 'DeepSeek',
    homepage: 'https://chat.deepseek.com/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'gemini-web',
    name: 'Gemini',
    vendor: 'Google',
    homepage: 'https://gemini.google.com/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    vendor: 'Google',
    homepage: 'https://github.com/google-gemini/gemini-cli',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'Gemini API key',
      docsUrl: 'https://ai.google.dev/gemini-api/docs/api-key',
    },
  },
  {
    id: 'goose',
    name: 'goose',
    vendor: 'Agentic AI Foundation (originally Block)',
    homepage: 'https://goose-docs.ai/',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
  },
  {
    id: 'grok-web',
    name: 'Grok',
    vendor: 'xAI',
    homepage: 'https://grok.com/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'grok',
    name: 'Grok Build',
    vendor: 'xAI',
    homepage: 'https://x.ai/grok',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'xAI API key',
      docsUrl: 'https://docs.x.ai/docs/overview',
    },
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    vendor: 'Element Labs',
    homepage: 'https://lmstudio.ai/',
    kinds: ['desktop-app', 'terminal'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
  {
    id: 'mistral-le-chat',
    name: 'Le Chat',
    vendor: 'Mistral AI',
    homepage: 'https://chat.mistral.ai/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'mistral-vibe',
    name: 'Mistral Vibe',
    vendor: 'Mistral AI',
    homepage: 'https://github.com/mistralai/mistral-vibe',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'off',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'Mistral API key',
      docsUrl: 'https://docs.mistral.ai/getting-started/quickstart/',
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    vendor: 'Ollama',
    homepage: 'https://ollama.com/',
    kinds: ['desktop-app', 'terminal'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    vendor: 'Anomaly (formerly SST)',
    homepage: 'https://opencode.ai/',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    vendor: 'Perplexity AI',
    homepage: 'https://www.perplexity.ai/',
    kinds: ['web-app'],
    group: 'web',
    planSignin: 'on',
    installable: false,
    sessions: false,
  },
  {
    id: 'qwen-code',
    name: 'Qwen Code',
    vendor: 'Alibaba Qwen',
    homepage: 'https://qwenlm.github.io/qwen-code-docs/en/',
    kinds: ['acp', 'terminal'],
    group: 'agent',
    planSignin: 'on',
    installable: true,
    sessions: true,
    apiKey: {
      label: 'OpenAI-compatible API key (also set OPENAI_BASE_URL and OPENAI_MODEL)',
      docsUrl: 'https://qwenlm.github.io/qwen-code-docs/en/users/configuration/auth/',
    },
  },
  {
    id: 'windsurf',
    name: 'Devin Desktop (formerly Windsurf)',
    vendor: 'Cognition',
    homepage: 'https://devin.ai/desktop',
    kinds: ['desktop-app'],
    group: 'desktop',
    planSignin: 'on',
    installable: true,
    sessions: false,
  },
];

export const catalogApp = (id: string): CatalogApp | undefined => CATALOG.find((a) => a.id === id);
