// Generated by `pnpm legal:hash`. Every archived legal version, by document.

import * as terminos_v1_0 from './terminos/v1-0';
import * as suscripcion_v1_0 from './suscripcion/v1-0';
import * as privacidad_v1_0 from './privacidad/v1-0';
import * as uso_aceptable_v1_0 from './uso_aceptable/v1-0';

export interface ArchivedVersion {
  version: string;
  sha256: string;
  source: string;
  template: string;
}

export const ARCHIVE: Record<string, Record<string, ArchivedVersion>> = {
  terminos: {
    '1.0': terminos_v1_0,
  },
  suscripcion: {
    '1.0': suscripcion_v1_0,
  },
  privacidad: {
    '1.0': privacidad_v1_0,
  },
  uso_aceptable: {
    '1.0': uso_aceptable_v1_0,
  },
};
